definitions:
  mysql.User:
    properties:
      password:
        type: string
      userName:
        type: string
    type: object
  v1.Resp:
    properties:
      code:
        type: string
      data:
        type: object
      msg:
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: demo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: demo
  version: "1.0"
paths:
  /v1/login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: post json参数
        in: body
        name: object
        schema:
          $ref: '#/definitions/mysql.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Resp'
      summary: 登录接口
      tags:
      - 登录
  /v1/logout:
    post:
      consumes:
      - application/json
      description: 注销接口
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Resp'
      security:
      - ApiKeyAuth: []
      summary: 注销接口
      tags:
      - 注销
  /v1/user:
    get:
      consumes:
      - application/json
      description: 获取用户信息接口
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - in: query
        name: password
        type: string
      - in: query
        name: userName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Resp'
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息接口
      tags:
      - 获取用户信息
swagger: "2.0"
